baseurl: https://suye.netlify.app/
languageCode: zh-Hans
defaultContentLanguage: en
title: Ye.S-HomePage
theme: hugo-theme-dream
menu:
  main:
    - name: About Me
      url: /aboutme
params:
  author: Su Ye
  avatar: /img/touxiang.jpg
  # background: '#f7f7f7'
  backgroundImage: "/img/day.jpg"
      
  # social_links
  email: small_black_luo@163.com
  github: suye0620
  telegram: suge_0620
  
  headerTitle: Ye.S-HomePage
  linkColor: seagreen
  motto: 得意淡然，失意坦然；喜而不狂，忧而不伤。
  siteStartYear: 2021
  hasCJKLanguage: true
  # enableSearch: true
  
  # dark mode
  # defaultDark = true
  # backgroundDark: "black"
  backgroundImageDark: "/img/night.jpeg"
  # darkLinkColor: "darkseagreen"
  # darkNav: true
  # dark404: true

  favicon: "/img/luoxiaohei.ico"
  
  # highlight
  highlightjs: true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages: ['ocaml']
  highlightjsTheme: "gruvbox-light"
  highlightjsThemeDark: "gruvbox-dark"
  
  # options
  toc: true
  showSummaryCoverInPost: true
  # hasTwitterEmbed = true
  # reversePostAndAside: true
  shareInAside: true
  fixedNav: yes
  # collapsibleTags = true
  # collapseBySummary = true
  
  # [params.advanced]经调整已经废置
  # customCSS: ["css/custom.css"]
  # customJSBefore = []
  # customJS = []

  # [params.experimental]
  # experimenta:
  #   jsDate: true
  #   jsDateFormat: "yyyy年MM月dd日"
  
  # [outputs]
  outputs:
    # home: ["HTML", "RSS", "JSON"]

    - html
    - rss
    - json
  
  enableEmoji: true

  # [Params]
  enableGitalk: true

  # [Params.Gitalk]
  Gitalk: 
    clientID: "93bba5e433f67f4139a5" # Your client ID
    clientSecret: "269de81a45529defdbb990ec6e75608320ba738c" # Your client secret
    repo: "suye0620/BeautifulBlog" # The repo to store comments
    owner: "suye0620" # Your GitHub ID
    admin: "suye0620" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id: "location.pathname" # The unique id of the page.
    labels: "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage: 5 # Pagination size, with maximum 100.
    pagerDirection: "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually: false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode: false # Enable hot key (cmd|ctrl + enter) submit comment.

# 支持HTML对Markdown进行排版
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes

